Repository vtex-sites/gatsby.store, pull requests merged in 2022-09, with the labels that each got.

#194 chore: Revisit `Hero` documentation (Storybook)
  src/components/sections/Hero/Hero.stories.mdx
  src/components/sections/Hero/Hero.stories.tsx
  src/components/sections/Hero/Hero.tsx
  src/components/sections/Hero/hero.module.scss
  src/components/sections/Hero/hero.scss
  src/components/sections/Hero/index.ts
  src/styles/global/storybook-components.scss
  src/styles/pages/homepage.scss
  src/styles/pages/plp.scss
Labels: Documentation, Chore

#200 fix: `view_item_list` event being fired without products
  cypress/integration/analytics.test.js
  src/components/sections/ProductShelf/ProductShelf.tsx
  src/components/sections/ProductTiles/ProductTiles.tsx
  src/components/sections/Section/Section.tsx
  src/sdk/search/Sentinel.tsx
Labels: Bug Fixes

#201 Feat: [Refinements] Creates `ShippingSimulation`
  src/components/regionalization/Regionalization.stories.mdx
  src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx
  src/components/regionalization/RegionalizationModal/RegionalizationModalContent.tsx
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/sections/ProductDetails/product-details.scss
  src/components/ui/ImageGallery/image-gallery.module.scss
  src/components/ui/InputText/InputText.tsx
  src/components/ui/ShippingSimulation/ShippingSimulation.stories.mdx
  src/components/ui/ShippingSimulation/ShippingSimulation.tsx
  src/components/ui/ShippingSimulation/index.tsx
  src/components/ui/ShippingSimulation/shipping-simulation.module.scss
  src/components/ui/ShippingSimulation/useShippingSimulation.ts
Labels: Documentation, Features

#204 feat: Fire `view_cart` event when the minicart is opened
  cypress/integration/analytics.test.js
  src/components/cart/CartSidebar/CartSidebar.tsx
Labels: Features

#203 fix: A regression with CLS on the Home page
  src/components/sections/ProductShelf/ProductShelf.tsx
  src/components/sections/ProductTiles/ProductTiles.tsx
Labels: Bug Fixes

#205 Fix: Product Details Grid (#236)
  .storybook/storybook.css
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/sections/ProductDetails/product-details.module.scss
  src/components/sections/ProductDetails/product-details.scss
  src/components/ui/ImageGallery/ImageGallery.stories.mdx
  src/components/ui/ImageGallery/ImageGallery.tsx
  src/components/ui/ImageGallery/image-gallery.module.scss
  src/components/ui/ProductTitle/product-title.module.scss
  src/components/ui/ShippingSimulation/ShippingSimulation.stories.mdx
  src/components/ui/ShippingSimulation/ShippingSimulation.tsx
  src/components/ui/ShippingSimulation/shipping-simulation.module.scss
  src/components/ui/SkuSelector/Selectors.tsx
  src/styles/global/storybook-components.scss
  src/styles/pages/pdp.scss
Labels: Bug Fixes
