Repository vtex-sites/gatsby.store, pull requests merged in 2022-10, with the labels that each got.

#216 chore: Renames data-attr
  src/components/cart/CartToggle/CartToggle.tsx
  src/components/cart/CartToggle/cart-toggle.scss
  src/components/common/Navbar/navbar.module.scss
Labels: Chore

#215 Feat: Adjust Newsletter to match new designs
  src/components/sections/BannerNewsletter/BannerNewsletter.tsx
  src/components/sections/BannerNewsletter/banner-newsletter.module.scss
  src/components/sections/BannerText/banner-text.scss
  src/components/sections/Newsletter/Newsletter.stories.mdx
  src/components/sections/Newsletter/Newsletter.tsx
  src/components/sections/Newsletter/newsletter.module.scss
  src/components/ui/Toast/Toast.stories.mdx
  src/components/ui/Toast/Toast.stories.tsx
  src/components/ui/Toast/toast.module.scss
  src/pages/[slug]/p.tsx
  src/pages/index.tsx
  static/icons.svg
Labels: Features

#202 chore: Improve deploy time with the new `USE_BUILD_CACHE`
  vtex.env
Labels: Chore

#207 chore: Resolve linting warnings and errors
  .eslintrc
  gatsby-config.ts
  gatsby-ssr.tsx
  src/components/cms/RenderPageSections.tsx
  src/components/ui/ShippingSimulation/useShippingSimulation.ts
  src/pages/[slug]/p.tsx
  src/server/index.ts
Labels: Chore

#211 fix: collection pages facets
  package.json
  yarn.lock
Labels: Bug Fixes

#222 chore: use transition api to defer navbar behavior
  src/sdk/ui/useScrollDirection.ts
Labels: Chore, Performance
