Repository vtex-sites/gatsby.store, pull requests merged in 2022-07, with the labels that each got.

#132 Feat: Adds new tokens to `Navbar`
  .storybook/storybook.css
  CHANGELOG.md
  README.md
  src/components/common/Navbar/NavLinks.stories.mdx
  src/components/common/Navbar/NavLinks.tsx
  src/components/common/Navbar/Navbar.stories.mdx
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/NavbarSlider.stories.mdx
  src/components/common/Navbar/NavbarSlider.tsx
  src/components/common/Navbar/index.tsx
  src/components/common/Navbar/navbar-slider.module.scss
  src/components/common/Navbar/navbar.module.scss
  src/components/common/Navbar/navbar.scss
  src/components/common/Navbar/navlinks.module.scss
  src/components/ui/Button/ButtonLink/ButtonSignIn/ButtonSignIn.tsx
  src/components/ui/Button/ButtonLink/ButtonSignIn/ButtonSignInFallback/ButtonSignInFallback.tsx
  src/styles/global/storybook-components.scss
  src/styles/pages/layout.scss
Labels: documentation, enhancement

#139 feat: Add priceCurrency to Offer
  CHANGELOG.md
  package.json
  yarn.lock
Labels: enhancement

#140 Chore: Storybook Docs Updates
  .storybook/storybook.css
  CHANGELOG.md
  src/components/cart/CartItem/CartItem.stories.mdx
  src/components/product/ProductCard/ProductCard.stories.tsx
  src/components/regionalization/RegionalizationModal/RegionalizationModal.stories.mdx
  src/components/sections/Hero/Hero.stories.tsx
  src/components/ui/Badge/Badge.stories.tsx
  src/components/ui/Badge/DiscountBadge.stories.tsx
  src/components/ui/Button/Button.stories.mdx
  src/components/ui/Dropdown/Dropdown.stories.mdx
  src/components/ui/EmptyState/EmptyState.stories.mdx
  src/components/ui/InputText/InputText.stories.tsx
  src/components/ui/Link/Link.stories.tsx
  src/components/ui/PriceRange/PriceRange.stories.mdx
  src/components/ui/ProductTitle/ProductTitle.stories.mdx
  src/components/ui/QuantitySelector/QuantitySelector.stories.mdx
  src/components/ui/Select/Select.stories.tsx
  src/components/ui/Toast/Toast.stories.tsx
  src/stories/colors.stories.mdx
  src/stories/getting-started.stories.mdx
  src/stories/global-tokens.stories.mdx
  src/stories/icons.stories.mdx
  src/stories/theming.stories.mdx
  src/styles/global/tokens.scss
Labels: documentation, chore

#145 fix: SonarQube warnings/error
  CHANGELOG.md
  src/Layout.tsx
  src/components/ui/Modal/Modal.tsx
  src/sdk/tests/index.tsx
  src/sdk/ui/Provider.tsx
Labels: chore

#142 Feat: Adds tokens to `SlideOver`
  .storybook/mocks/cart-sidebar.js
  .storybook/mocks/filter-slider.js
  CHANGELOG.md
  src/components/cart/CartSidebar/CartSidebar.stories.mdx
  src/components/cart/CartSidebar/CartSidebar.tsx
  src/components/cart/CartSidebar/cart-sidebar.module.scss
  src/components/cart/CartSidebar/cart-sidebar.scss
  src/components/ui/SlideOver/SlideOver.stories.mdx
  src/components/ui/SlideOver/SlideOver.tsx
  src/components/ui/SlideOver/overlay.scss
  src/components/ui/SlideOver/slide-over.module.scss
  src/components/ui/SlideOver/slide-over.scss
  src/styles/global/storybook-components.scss
  src/styles/pages/layout.scss
Labels: documentation, enhancement

#146 Feat: Adds new tokens to `Breadcrumb`
  CHANGELOG.md
  src/components/ui/Breadcrumb/Breadcrumb.stories.mdx
  src/components/ui/Breadcrumb/Breadcrumb.stories.tsx
  src/components/ui/Breadcrumb/Breadcrumb.tsx
  src/components/ui/Breadcrumb/breadcrumb.module.scss
  src/components/ui/Breadcrumb/breadcrumb.scss
  src/components/ui/Dropdown/DropdownItem.stories.mdx
  src/components/ui/Dropdown/DropdownItem.tsx
  src/components/ui/Dropdown/dropdown.module.scss
  src/styles/global/storybook-components.scss
  src/styles/pages/pdp.scss
  src/styles/pages/plp.scss
  src/styles/pages/search.scss
  static/icons.svg
Labels: documentation, enhancement

#144 fix: Transfers responsibility of `InputText`'s main attributes and callbacks to the renderer
  CHANGELOG.md
  src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx
  src/components/ui/InputText/InputText.stories.tsx
  src/components/ui/InputText/InputText.tsx
Labels: bug

#147 Feat: adds tokens to `Footer`
  .storybook/components/SectionItem.tsx
  .storybook/storybook.css
  CHANGELOG.md
  src/components/common/Footer/Footer.stories.mdx
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/FooterLinks.tsx
  src/components/common/Footer/footer.module.scss
  src/components/common/Footer/footer.scss
  src/components/sections/Incentives/Incentives.stories.mdx
  src/components/sections/Incentives/Incentives.tsx
  src/components/sections/Incentives/IncentivesFooter.tsx
  src/components/sections/Incentives/incentives.module.scss
  src/components/sections/Incentives/incentivesMock.js
  src/components/sections/Incentives/incentivesMock.ts
  src/pages/index.tsx
  src/styles/global/storybook-components.scss
  src/styles/pages/layout.scss
Labels: documentation, enhancement

#148 chore: Improve integration tests by upgrading Cypress to 9.6.5
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore

#150 Feat: Add css modules, tokens and refactor `Search` components
  .storybook/components/SectionItem.tsx
  .storybook/mocks/index.ts
  .storybook/mocks/searchHistory.ts
  .storybook/mocks/searchTerms.ts
  CHANGELOG.md
  src/components/common/Navbar/Navbar.tsx
  src/components/common/SearchInput/index.tsx
  src/components/search/History/SearchHistory.stories.tsx
  src/components/search/Search.stories.mdx
  src/components/search/SearchDropdown/SearchDropdown.stories.mdx
  src/components/search/SearchDropdown/SearchDropdown.tsx
  src/components/search/SearchDropdown/index.ts
  src/components/search/SearchHistory/SearchHistory.stories.mdx
  src/components/search/SearchHistory/SearchHistory.tsx
  src/components/search/SearchHistory/index.tsx
  src/components/search/SearchInput/SearchInput.stories.mdx
  src/components/search/SearchInput/SearchInput.tsx
  src/components/search/SearchInput/index.tsx
  src/components/search/SearchInput/search-input.scss
  src/components/search/SearchProductCard/SearchProductCard.stories.mdx
  src/components/search/SearchProductCard/SearchProductCard.tsx
  src/components/search/SearchProductCard/index.ts
  src/components/search/SearchProductCard/search-product-card.module.scss
  src/components/search/SearchSharedTokenTable.mdx
  src/components/search/SearchSuggestions/SearchSuggestions.stories.mdx
  src/components/search/SearchSuggestions/SearchSuggestions.tsx
  src/components/search/SearchSuggestions/index.ts
  src/components/search/SearchTop/SearchTop.stories.mdx
  src/components/search/SearchTop/SearchTop.tsx
  src/components/search/SearchTop/index.ts
  src/components/search/SuggestionProductCard/index.ts
  src/components/search/SuggestionProductCard/suggestion-product-card.module.scss
  src/components/search/Suggestions/Suggestions.tsx
  src/components/search/Suggestions/SuggestionsTopSearch.stories.tsx
  src/components/search/Suggestions/SuggestionsTopSearch.tsx
  src/components/search/Suggestions/index.ts
  src/components/search/Suggestions/suggestions.scss
  src/components/search/search.module.scss
  src/components/search/searchMock.ts
  src/components/ui/Search/Suggestions/Suggestions.stories.tsx
  src/components/ui/Search/Suggestions/index.ts
  src/styles/global/storybook-components.scss
  src/styles/pages/layout.scss
Labels: documentation, enhancement

#151 chore: Improve integration tests by upgrading Cypress to 9.6.0
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore

#153 chore: automatic changelog releases
  .github/workflows/release.yml
  .release-it.json
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore

#157 fix: prettier ignore auto-generated file
  .prettierignore
  static/mockServiceWorker.js
Labels: chore

#159 Fix/restore deleted changelog entries
  CHANGELOG.md
Labels: chore
