Repository vtex-sites/gatsby.store, pull requests merged in 2022-05, with the labels that each got.

#20 fix: Fix missing styles
  CHANGELOG.md
  cypress/integration/cart.test.js
  src/components/sections/ProductGallery/product-gallery.scss
  src/components/ui/EmptyState/EmptyState.tsx
  src/components/ui/EmptyState/empty-state.scss
  src/styles/pages/homepage.scss
  src/styles/pages/layout.scss
  src/styles/pages/pdp.scss
  src/styles/pages/plp.scss
  src/styles/pages/search.scss
Labels: bug

#19 feat: Adds new tokens to Link
  CHANGELOG.md
  src/components/ui/Link/Link.stories.tsx
  src/components/ui/Link/Link.tsx
  src/components/ui/Link/index.ts
  src/components/ui/Link/index.tsx
  src/components/ui/Link/link.scss
Labels: chore

#17 feat: Adds new tokens to Select
  CHANGELOG.md
  src/components/search/Sort/Sort.tsx
  src/components/ui/Select/Select.stories.tsx
  src/components/ui/Select/Select.tsx
  src/components/ui/Select/index.ts
  src/components/ui/Select/index.tsx
  src/components/ui/Select/select.scss
Labels: chore

#10 chore: home performance improvements
  CHANGELOG.md
  package.json
  src/Layout.tsx
  src/components/sections/ProductShelf/ProductShelf.tsx
  src/components/sections/ProductTiles/ProductTiles.tsx
  src/pages/[slug]/p.tsx
  src/pages/index.tsx
  src/sdk/person/usePersonQuery.ts
  yarn.lock
Labels: performance

#25 chore: Rename Badge prop
  CHANGELOG.md
  src/components/ui/Badge/Badge.stories.tsx
  src/components/ui/Badge/Badge.tsx
  src/components/ui/Badge/badge.scss
Labels: chore

#3 fix: Hydration mismatch
  CHANGELOG.md
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/sections/ProductGallery/useDelayedPagination.ts
Labels: bug

#27 fix: Toggle arrows at the ImageGallery in accordance to scroll position
  CHANGELOG.md
  src/components/ui/Image/Image.tsx
  src/components/ui/ImageGallery/ImageGallerySelector.tsx
  src/components/ui/ImageGallery/image-gallery-selector.scss
Labels: enhancement

#24 chore: Better organize the Changelog
  CHANGELOG.md
Labels: chore

#7 chore: Organize some search components
  CHANGELOG.md
  src/components/search/History/SearchHistory.stories.tsx
  src/components/search/History/SearchHistory.tsx
  src/components/search/History/index.tsx
  src/components/search/History/search-history.scss
  src/components/search/Suggestions/Suggestions.tsx
  src/components/search/Suggestions/SuggestionsTopSearch.stories.tsx
  src/components/search/Suggestions/SuggestionsTopSearch.tsx
  src/components/search/Suggestions/index.ts
  src/components/ui/Search/Suggestions/Suggestions.stories.tsx
  src/components/ui/Search/Suggestions/Suggestions.tsx
  src/components/ui/Search/Suggestions/index.ts
  src/sdk/search/useSearchHistory.ts
  src/styles/global/storybook-components.scss
  static/icons.svg
Labels: bug, enhancement

#23 chore: Show more details about failed accessibility tests
  CHANGELOG.md
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
Labels: chore

#40 chore: FSSS-280 Code Improvements
  CHANGELOG.md
  src/components/ui/ImageGallery/ImageGallerySelector.tsx
Labels: chore

#42 fix: Promotions
  package.json
  src/server/index.ts
  yarn.lock
Labels: bug

#43 Feat/add analytics to cart item
  CHANGELOG.md
  src/components/cart/CartItem/CartItem.tsx
Labels: enhancement

#48 fix: Resolves `@reach/router` on storybook
  .storybook/main.js
  CHANGELOG.md
Labels: bug

#34 Feat: Uses `ProductCard` component from FSUI
  CHANGELOG.md
  cypress/integration/analytics.test.js
  cypress/integration/plp.test.js
  src/components/product/ProductCard/ProductCard.tsx
  src/components/product/ProductCard/product-card.scss
Labels: chore

#26 Feat: Unify Storybook Documentation
  .storybook/preview.js
  .storybook/storybook.css
  .storybook/theme.js
  CHANGELOG.md
  src/components/product/ProductCard/product-card.scss
  src/components/sections/BannerText/BannerText.stories.mdx
  src/components/sections/BannerText/BannerText.stories.tsx
  src/components/sections/BannerText/banner-text.scss
  src/components/ui/Hero/hero.scss
  src/components/ui/InputText/input-text.scss
  src/components/ui/Link/link.scss
  src/components/ui/Select/select.scss
  src/components/ui/Toggle/Toggle.stories.mdx
  src/components/ui/Toggle/Toggle.stories.tsx
  src/components/ui/Toggle/Toggle.tsx
  src/components/ui/Toggle/toggle.scss
  src/stories/colors.stories.mdx
  src/stories/getting-started.stories.mdx
  src/stories/icons.stories.mdx
  src/stories/theming.stories.mdx
  src/stories/typography.stories.mdx
  src/styles/global/tokens.scss
Labels: documentation, chore

#50 fix: Breadcrumb broken links
  package.json
  yarn.lock
Labels: bug

#28 feat: Style Toast component
  CHANGELOG.md
  README.md
  src/Layout.tsx
  src/components/cart/CartItem/cart-item.scss
  src/components/common/Footer/footer.scss
  src/components/common/Navbar/navbar.scss
  src/components/common/SearchInput/search-input.scss
  src/components/product/ProductCard/product-card.scss
  src/components/regionalization/RegionalizationButton/regionalization-button.scss
  src/components/search/Filter/filter.scss
  src/components/search/SuggestionProductCard/suggestion-product-card.scss
  src/components/search/Suggestions/suggestions.scss
  src/components/sections/ProductDetails/product-details.scss
  src/components/sections/Section/section.scss
  src/components/skeletons/FilterSkeleton/filter-skeleton.scss
  src/components/skeletons/ProductCardSkeleton/product-card-skeleton.scss
  src/components/skeletons/ProductTilesSkeleton/ProductTileSkeleton/product-tile-skeleton.scss
  src/components/skeletons/SkeletonElement/skeleton-element.scss
  src/components/ui/Badge/badge.scss
  src/components/ui/Breadcrumb/breadcrumb.scss
  src/components/ui/Button/button.scss
  src/components/ui/Checkbox/checkbox.scss
  src/components/ui/EmptyState/empty-state.scss
  src/components/ui/ImageGallery/image-gallery-selector.module.scss
  src/components/ui/ImageGallery/image-gallery.module.scss
  src/components/ui/InputText/input-text.scss
  src/components/ui/Link/link.scss
  src/components/ui/QuantitySelector/quantity-selector.scss
  src/components/ui/Select/select.scss
  src/components/ui/SkuSelector/sku-selector.scss
  src/components/ui/Tiles/tiles.scss
  src/components/ui/Toast/Toast.stories.tsx
  src/components/ui/Toast/Toast.tsx
  src/components/ui/Toast/toast.scss
  src/components/ui/Toggle/toggle.scss
  src/sdk/ui/index.tsx
  src/styles/global/storybook-components.scss
  src/styles/global/tokens.scss
  src/styles/global/utilities.scss
  src/styles/pages/layout.scss
  static/icons.svg
Labels: enhancement

#51 Improve LCP by setting a higher fetch priority
  CHANGELOG.md
  src/components/sections/Hero/Hero.tsx
  src/components/ui/Image/Image.tsx
  src/components/ui/ImageGallery/ImageGallery.tsx
Labels: performance

#59 Chore: Upgrade Gatsby@4.14
  CHANGELOG.md
  package.json
  yarn.lock
Labels: enhancement, performance

#60 fix: Fixes custom attributes for `img` and `link` tags
  CHANGELOG.md
  src/components/sections/Hero/Hero.tsx
  src/components/ui/Image/Image.tsx
  src/components/ui/ImageGallery/ImageGallery.tsx
Labels: bug

#65 fix: Fixes <link /> attribute typo
  src/components/ui/Image/Image.tsx
Labels: bug

#80 Doc: fixed doc responsible names
  pull_request_template.md
Labels: documentation
