Repository vtex-sites/gatsby.store, pull requests merged in 2022-06, with the labels that each got.

#85 feat: Add document in `QuantitySelector`
  .storybook/components/TokenDivider.tsx
  .storybook/components/TokenRow.tsx
  .storybook/components/TokenTable.tsx
  .storybook/components/index.ts
  CHANGELOG.md
  src/components/ui/QuantitySelector/QuantitySelector.stories.mdx
  src/components/ui/QuantitySelector/QuantitySelector.tsx
Labels: documentation

#86 fix: Static incremental builds errors
  src/pages/[...slug].tsx
  src/pages/[slug]/p.tsx
Labels: bug

#77 Feat: Adds tokens to `Alert`
  CHANGELOG.md
  src/components/ui/Alert/Alert.stories.mdx
  src/components/ui/Alert/Alert.tsx
  src/components/ui/Alert/alert.module.scss
  src/components/ui/Alert/alert.scss
  src/styles/global/storybook-components.scss
  src/styles/pages/layout.scss
Labels: enhancement

#92 Feat: Uses Hero component from FSUI
  CHANGELOG.md
  package.json
  src/components/sections/Hero/Hero.tsx
  src/components/sections/Hero/hero.scss
  src/components/ui/Hero/Hero.tsx
  src/components/ui/Hero/HeroContent.tsx
  src/components/ui/Hero/HeroImage.tsx
  src/components/ui/Hero/HeroLink.tsx
  src/components/ui/Hero/index.ts
  src/pages/index.tsx
  src/styles/global/storybook-components.scss
  src/styles/pages/homepage.scss
  src/styles/pages/plp.scss
  yarn.lock
Labels: chore

#89 Feat: Adds tokens to `Radio`
  .storybook/storybook.css
  CHANGELOG.md
  src/components/ui/Checkbox/Checkbox.stories.mdx
  src/components/ui/Checkbox/checkbox.module.scss
  src/components/ui/Radio/Radio.stories.mdx
  src/components/ui/Radio/Radio.tsx
  src/components/ui/Radio/index.tsx
  src/components/ui/Radio/radio.module.scss
Labels: enhancement, chore

#96 Chore: Improves rows and dividers on storybook
  .storybook/components/TokenDivider.tsx
  .storybook/storybook.css
  CHANGELOG.md
Labels: chore

#98 fix: Region Input
  CHANGELOG.md
  src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx
Labels: bug

#93 chore: Single UI Provider
  CHANGELOG.md
  gatsby-browser.tsx
  gatsby-ssr.tsx
  src/Layout.tsx
  src/components/cart/CartSidebar/CartSidebar.tsx
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Toast/Toast.tsx
  src/components/regionalization/RegionalizationBar/RegionalizationBar.tsx
  src/components/regionalization/RegionalizationButton/RegionalizationButton.tsx
  src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx
  src/components/regionalization/RegionalizationModal/RegionalizationModal.tsx
  src/components/search/Filter/Filter.tsx
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/ui/SlideOver/SlideOver.tsx
  src/components/ui/Toast/Toast.stories.tsx
  src/components/ui/Toast/Toast.tsx
  src/sdk/cart/useBuyButton.ts
  src/sdk/cart/useCartToggleButton.ts
  src/sdk/ui/Provider.tsx
  src/sdk/ui/index.tsx
  src/sdk/ui/modal/Provider.tsx
  src/sdk/ui/modal/index.ts
  src/sdk/ui/useFadeEffect.ts
Labels: enhancement

#105 fix: duplicated query at `useTopSearch` hook
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  CHANGELOG.md
  src/sdk/search/useTopSearch.ts
Labels: bug

#108 fix: Page error codes
  CHANGELOG.md
  package.json
  src/api/graphql.ts
  src/pages/[...slug].tsx
  src/pages/[slug]/p.tsx
  src/server/index.ts
  yarn.lock
Labels: bug

#87 feat: Canonical PDP slugs
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  CHANGELOG.md
  cypress/integration/seo.test.js
  package.json
  src/pages/[...slug].tsx
  src/pages/[slug]/p.tsx
  src/pages/index.tsx
  src/server/index.ts
  store.config.js
  yarn.lock
Labels: enhancement

#103 chore: Unify Link usage
  CHANGELOG.md
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/FooterLinks.tsx
  src/components/common/Footer/footer.scss
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/navbar.scss
  src/components/common/SearchInput/search-input.scss
  src/components/product/ProductCard/ProductCard.tsx
  src/components/product/ProductCard/product-card.module.scss
  src/components/regionalization/RegionalizationModal/RegionalizationModal.tsx
  src/components/regionalization/RegionalizationModal/regionalization-modal.scss
  src/components/search/History/SearchHistory.tsx
  src/components/search/SuggestionProductCard/SuggestionProductCard.tsx
  src/components/search/SuggestionProductCard/suggestion-product-card.scss
  src/components/search/Suggestions/SuggestionsTopSearch.tsx
  src/components/search/Suggestions/suggestions.scss
  src/components/sections/BannerText/BannerText.tsx
  src/components/sections/BannerText/banner-text.scss
  src/components/sections/Hero/Hero.tsx
  src/components/sections/ProductGallery/EmptyGallery.tsx
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/ui/Alert/Alert.tsx
  src/components/ui/Breadcrumb/Breadcrumb.tsx
  src/components/ui/Breadcrumb/breadcrumb.scss
  src/components/ui/Button/ButtonLink/ButtonLink.tsx
  src/components/ui/Button/ButtonLink/ButtonSignIn/ButtonSignIn.tsx
  src/components/ui/Button/ButtonLink/ButtonSignIn/ButtonSignInFallback/ButtonSignInFallback.tsx
  src/components/ui/EmptyState/empty-state.scss
  src/components/ui/Link/Link.stories.tsx
  src/components/ui/Link/Link.tsx
  src/components/ui/Link/link.module.scss
  src/components/ui/Search/Suggestions/Suggestions.tsx
  src/sdk/product/useProductLink.ts
Labels: chore

#110 Feat: Best Practices Section
  .storybook/components/BestPractices.tsx
  .storybook/components/BestPracticesRule.tsx
  .storybook/components/TokenRow.tsx
  .storybook/components/index.ts
  .storybook/storybook.css
  CHANGELOG.md
  src/components/ui/Alert/Alert.stories.mdx
  src/components/ui/Alert/Alert.tsx
  src/components/ui/Button/Button.stories.mdx
Labels: chore

#109 chore: Upgrade Storybook from 6.4.20 to 6.5.9
  .storybook/main.js
  CHANGELOG.md
  package.json
  yarn.lock
Labels: chore

#111 Feat: Extract and adds tokens to Dropdown
  CHANGELOG.md
  src/components/ui/Breadcrumb/Breadcrumb.stories.tsx
  src/components/ui/Breadcrumb/Breadcrumb.tsx
  src/components/ui/Breadcrumb/breadcrumb.scss
  src/components/ui/Dropdown/Dropdown.stories.mdx
  src/components/ui/Dropdown/Dropdown.tsx
  src/components/ui/Dropdown/DropdownButton.tsx
  src/components/ui/Dropdown/DropdownItem.stories.mdx
  src/components/ui/Dropdown/DropdownItem.tsx
  src/components/ui/Dropdown/DropdownMenu.stories.mdx
  src/components/ui/Dropdown/DropdownMenu.tsx
  src/components/ui/Dropdown/dropdown.module.scss
  src/components/ui/Dropdown/index.tsx
  static/icons.svg
Labels: chore

#113 Feat: Adds tokens to `EmptyState`
  CHANGELOG.md
  src/components/cart/EmptyCart/EmptyCart.tsx
  src/components/sections/ProductGallery/EmptyGallery.tsx
  src/components/ui/EmptyState/EmptyState.stories.mdx
  src/components/ui/EmptyState/EmptyState.tsx
  src/components/ui/EmptyState/empty-state.module.scss
  src/components/ui/EmptyState/empty-state.scss
  src/styles/global/storybook-components.scss
  src/styles/pages/layout.scss
Labels: documentation, enhancement, chore

#114 chore: Upgrade dependencies
  .storybook/main.js
  CHANGELOG.md
  codegen.yml
  gatsby-node.ts
  lighthouserc.js
  package.json
  src/components/sections/ProductGallery/useGalleryQuery.ts
  src/pages/[...slug].tsx
  src/pages/[slug]/p.tsx
  src/sdk/cart/validate.ts
  src/sdk/graphql/request.ts
  src/sdk/product/useProduct.ts
  src/sdk/product/useProductsQuery.ts
  src/sdk/search/useSuggestions.ts
  src/sdk/search/useTopSearch.ts
  src/sdk/session/validate.ts
  yarn.lock
Labels: enhancement, breaking change

#112 feat: Price range filter on PLP
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  CHANGELOG.md
  codegen.yml
  cypress/integration/plp.test.js
  gatsby-ssr.tsx
  package.json
  src/components/search/Filter/Facets.tsx
  src/components/search/Filter/Filter.tsx
  src/components/search/Filter/useFilter.ts
  src/components/search/Sort/Sort.tsx
  src/components/sections/ProductGallery/useGalleryQuery.ts
  src/components/ui/PriceRange/PriceRange.stories.mdx
  src/components/ui/PriceRange/PriceRange.tsx
  src/components/ui/PriceRange/index.ts
  src/components/ui/PriceRange/price-range.module.scss
  src/pages/[...slug].tsx
  src/sdk/error/ErrorBoundary/ErrorBoundary.tsx
  src/sdk/graphql/prefetchQuery.ts
  src/sdk/product/useFormattedPrice.ts
  src/sdk/product/useProductsQuery.ts
  src/server/index.ts
  yarn.lock
Labels: enhancement

#115 Chore: storybook improvements
  .storybook/main.js
  .storybook/preview.js
  .storybook/storybook.css
  CHANGELOG.md
  src/components/ui/Checkbox/Checkbox.stories.mdx
  src/components/ui/Radio/Radio.stories.mdx
  src/components/ui/Toggle/Toggle.stories.mdx
  src/stories/changelog-template.stories.mdx
  src/stories/colors.stories.mdx
  src/stories/getting-started.stories.mdx
  src/stories/icons.stories.mdx
  src/stories/theming.stories.mdx
  src/stories/typography.stories.mdx
Labels: enhancement, chore

#116 chore: Remove logo from code
  .storybook/theme.js
  CHANGELOG.md
  src/components/common/Footer/Footer.tsx
  src/components/ui/Logo/Logo.tsx
  static/logo.svg
Labels: performance

#124 Feat: `Regionalization` Doc Storybook
  .storybook/preview.js
  .storybook/storybook.css
  CHANGELOG.md
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/navbar.scss
  src/components/regionalization/Regionalization.stories.mdx
  src/components/regionalization/RegionalizationBar/RegionalizationBar.stories.mdx
  src/components/regionalization/RegionalizationBar/RegionalizationBar.tsx
  src/components/regionalization/RegionalizationBar/regionalization-bar.module.scss
  src/components/regionalization/RegionalizationBar/regionalization-bar.scss
  src/components/regionalization/RegionalizationButton/RegionalizationButton.tsx
  src/components/regionalization/RegionalizationButton/regionalization-button.scss
  src/components/ui/Modal/Modal.stories.mdx
  src/stories/getting-started.stories.mdx
  src/stories/theming.stories.mdx
  src/styles/pages/layout.scss
Labels: documentation, enhancement

#125 Feat: Adds tokens to `ImageGallery`
  CHANGELOG.md
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/ui/Image/Image.tsx
  src/components/ui/Image/image.scss
  src/components/ui/ImageGallery/Icons.tsx
  src/components/ui/ImageGallery/ImageGallery.stories.mdx
  src/components/ui/ImageGallery/ImageGallerySelector.tsx
  src/components/ui/ImageGallery/image-gallery-selector.module.scss
  src/components/ui/ImageGallery/image-gallery.module.scss
  src/styles/global/layout.scss
  src/styles/global/storybook-components.scss
  src/styles/pages/layout.scss
Labels: documentation, enhancement

#126 Feat: Adds tokens to Accordion
  CHANGELOG.md
  src/components/common/Footer/footer.scss
  src/components/search/Filter/filter.scss
  src/components/ui/Accordion/Accordion.stories.mdx
  src/components/ui/Accordion/Accordion.tsx
  src/components/ui/Accordion/AccordionItem.stories.mdx
  src/components/ui/Accordion/AccordionItem.tsx
  src/components/ui/Accordion/accordion.module.scss
  src/components/ui/Accordion/accordion.scss
  src/styles/global/storybook-components.scss
  src/styles/pages/layout.scss
Labels: documentation, chore

#120 feat: Adds new tokens to `Tiles`
  .storybook/components/Callout.tsx
  .storybook/components/index.ts
  .storybook/storybook.css
  CHANGELOG.md
  src/components/sections/ProductGallery/product-gallery.module.scss
  src/components/sections/ProductTiles/ProductTiles.tsx
  src/components/ui/Tiles/Tile.tsx
  src/components/ui/Tiles/Tiles.stories.mdx
  src/components/ui/Tiles/Tiles.tsx
  src/components/ui/Tiles/index.ts
  src/components/ui/Tiles/tiles.module.scss
  src/components/ui/Tiles/tiles.scss
  src/stories/getting-started.stories.mdx
  src/styles/global/storybook-components.scss
  src/styles/pages/homepage.scss
  src/styles/pages/plp.scss
Labels: chore

#127 Feat: Adds tokens to `ProductGrid`
  .storybook/components/BestPractices.tsx
  .storybook/components/BestPracticesRule.tsx
  .storybook/mocks/productGridItems.js
  CHANGELOG.md
  src/components/product/ProductCard/product-card.module.scss
  src/components/product/ProductGrid/ProductGrid.stories.mdx
  src/components/product/ProductGrid/ProductGrid.tsx
  src/components/product/ProductGrid/product-grid.module.scss
  src/components/ui/Alert/Alert.stories.mdx
Labels: documentation, enhancement
