Repository vtex-sites/gatsby.store, pull requests merged in 2022-08, with the labels that each got.

#162 feat: Adds new tokens to `Skeleton` [FS-269]
  .storybook/storybook.css
  src/components/sections/ProductGallery/ProductGallery.tsx
  src/components/sections/ProductGallery/product-gallery.module.scss
  src/components/sections/ProductShelf/ProductShelf.tsx
  src/components/sections/ProductShelf/product-shelf.module.scss
  src/components/skeletons/FilterSkeleton/FilterSkeleton.stories.mdx
  src/components/skeletons/FilterSkeleton/FilterSkeleton.tsx
  src/components/skeletons/FilterSkeleton/filter-skeleton.module.scss
  src/components/skeletons/FilterSkeleton/filter-skeleton.scss
  src/components/skeletons/ProductCardSkeleton/ProductCardSkeleton.stories.mdx
  src/components/skeletons/ProductCardSkeleton/ProductCardSkeleton.tsx
  src/components/skeletons/ProductCardSkeleton/product-card-skeleton.module.scss
  src/components/skeletons/ProductCardSkeleton/product-card-skeleton.scss
  src/components/skeletons/ProductGridSkeleton/ProductGridSkeleton.tsx
  src/components/skeletons/ProductShelfSkeleton/ProductShelfSkeleton.tsx
  src/components/skeletons/ProductTilesSkeleton/ProductTileSkeleton/ProductTileSkeleton.tsx
  src/components/skeletons/ProductTilesSkeleton/ProductTileSkeleton/product-tile-skeleton.module.scss
  src/components/skeletons/ProductTilesSkeleton/ProductTileSkeleton/product-tile-skeleton.scss
  src/components/skeletons/ProductTilesSkeleton/ProductTilesSkeleton.tsx
  src/components/skeletons/ProductTilesSkeleton/index.ts
  src/components/skeletons/Shimmer/Shimmer.tsx
  src/components/skeletons/Shimmer/shimmer.module.scss
  src/components/skeletons/Shimmer/shimmer.scss
  src/components/skeletons/Skeleton/Skeleton.tsx
  src/components/skeletons/Skeleton/index.ts
  src/components/skeletons/Skeleton/skeleton.module.scss
  src/components/skeletons/SkeletonElement/SkeletonElement.tsx
  src/components/skeletons/SkeletonElement/index.ts
  src/components/skeletons/SkeletonElement/skeleton-element.scss
  src/components/skeletons/Skeletons.stories.mdx
  src/styles/global/storybook-components.scss
  src/styles/pages/homepage.scss
  src/styles/pages/pdp.scss
  src/styles/pages/plp.scss
  src/styles/pages/search.scss
Labels: enhancement

#164 feat: Add `ProductTitle` import from faststore
  CHANGELOG.md
  package.json
  src/components/ui/ProductTitle/ProductTitle.stories.mdx
  src/components/ui/ProductTitle/ProductTitle.tsx
  src/components/ui/ProductTitle/product-title.module.scss
  yarn.lock
Labels: enhancement

#165 Feat: adds tokens to `PriceRange`
  src/components/ui/InputText/input-text.scss
  src/components/ui/PriceRange/PriceRange.stories.mdx
  src/components/ui/PriceRange/PriceRange.tsx
  src/components/ui/PriceRange/price-range.module.scss
  src/sdk/product/useFormattedPrice.ts
  src/styles/global/tokens.scss
Labels: documentation, enhancement

#168 chore: Updates `BannerText` content example
  src/components/sections/BannerText/BannerText.stories.mdx
  src/pages/index.tsx
Labels: Chore

#166 feat: Working `SkuSelector` component
  @generated/graphql/index.ts
  @generated/graphql/persisted.json
  package.json
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/ui/SkuSelector/Selectors.tsx
  src/components/ui/SkuSelector/SkuSelector.tsx
  src/components/ui/SkuSelector/sku-selector.scss
  src/components/ui/SkuSelector/skuVariants.ts
  src/styles/pages/pdp.scss
  yarn.lock
Labels: Features

#176 fix: Avoids performing the search when user abandons the query
  src/components/common/Navbar/Navbar.tsx
  src/components/search/SearchInput/SearchInput.tsx
  src/components/search/SearchInput/index.tsx
Labels: Bug Fixes

#175 feat: Add new tokens to `SearchInput`
  src/components/common/Navbar/navbar.module.scss
  src/components/search/SearchInput/SearchInput.stories.mdx
  src/components/search/SearchInput/SearchInput.tsx
  src/components/search/SearchInput/search-input.module.scss
  src/components/search/SearchInput/search-input.scss
  src/styles/global/storybook-components.scss
  src/styles/pages/layout.scss
Labels: Features

#174 feat: Refinements on `Navbar` and `Navlinks`
  src/components/common/Navbar/NavLinks.stories.mdx
  src/components/common/Navbar/NavLinks.tsx
  src/components/common/Navbar/Navbar.stories.mdx
  src/components/common/Navbar/Navbar.tsx
  src/components/common/Navbar/navbar.module.scss
  src/components/common/Navbar/navlinks.module.scss
  src/sdk/ui/useScrollDirection.ts
  src/styles/global/tokens.scss
Labels: Documentation, Features

#178 Chore: Adds `InputText` documentation to storybook
  src/components/ui/InputText/InputText.stories.mdx
  src/components/ui/InputText/InputText.stories.tsx
  src/components/ui/InputText/InputText.tsx
  src/components/ui/InputText/input-text.module.scss
  src/components/ui/InputText/input-text.scss
  src/styles/global/storybook-components.scss
  src/styles/pages/layout.scss
Labels: Documentation, Chore

#177 feat: Handles `OutOfStock` error message through `InputText`'s error prop
  src/components/product/OutOfStock/OutOfStock.tsx
Labels: Features

#179 feat: Add new tokens to `SkuSelector`
  src/components/sections/ProductDetails/ProductDetails.tsx
  src/components/ui/SkuSelector/Selectors.stories.mdx
  src/components/ui/SkuSelector/Selectors.tsx
  src/components/ui/SkuSelector/SkuSelector.stories.mdx
  src/components/ui/SkuSelector/SkuSelector.tsx
  src/components/ui/SkuSelector/index.ts
  src/components/ui/SkuSelector/index.tsx
  src/components/ui/SkuSelector/sku-selector.module.scss
  src/components/ui/SkuSelector/sku-selector.scss
  src/styles/pages/pdp.scss
Labels: Features

#186 fix: Display `SearchDropdown` correctly
  .storybook/storybook.css
  src/components/common/Navbar/navlinks.module.scss
Labels: Bug Fixes

#172 Feat: integrate with client-cms
  CHANGELOG.md
  README.md
  cms-webhook-urls.json
  cms/content-types.json
  cms/sections.json
  cms/translation-keys.json
  package.json
  src/cms/client.ts
  src/components/cms/RenderPageSections.tsx
  src/pages/index.tsx
  store.config.js
  yarn.lock
Labels: Features

#189 fix: Fix cms config
  cms/sections.json
Labels: Bug Fixes

#188 chore: Renames/Updates breakpoints tokens
  src/components/sections/Hero/hero.scss
  src/stories/typography.stories.mdx
  src/styles/global/tokens.scss
Labels: Chore

#184 chore: Renames/Updates border tokens
  src/stories/refinements.stories.mdx
  src/styles/global/tokens.scss
Labels: Documentation, Chore

#193 chore: Include `Button` with only an icon on Storybook
  .storybook/storybook.css
  src/components/ui/Button/Button.stories.mdx
  src/components/ui/Button/button.module.scss
Labels: Documentation, Chore

#195 fix: Navigation links on mobile not being clickable
  src/components/common/Navbar/navlinks.module.scss
Labels: Bug Fixes
